package com.hadoop.friend_recommendation;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.conf.Configured;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Job;
import org.apache.hadoop.mapreduce.lib.input.FileInputFormat;
import org.apache.hadoop.mapreduce.lib.join.TupleWritable;
import org.apache.hadoop.mapreduce.lib.output.FileOutputFormat;
import org.apache.hadoop.util.Tool;
import org.apache.hadoop.util.ToolRunner;
import org.apache.log4j.Logger;

/**
 * Created by zhao on 2018-03-06.
 */
public class FriendReCommendationDriver extends Configured implements Tool {

    private static final Logger THE_LOGGER = Logger.getLogger(FriendReCommendationDriver.class);

    /**
     * Dispatches command-line arguments to the tool by the ToolRunner.
     */
    public static void main(String[] args) throws Exception {

        if (args.length < 2){
            throw new IllegalArgumentException("Usage: FriendReCommendation <inputFile>,<outputFile>,[neighborWindow]");
        }
        int runStatus = ToolRunner.run(new FriendReCommendationDriver(), args);
        System.exit(runStatus);
    }

    @Override
    public int run(String[] args) throws Exception {
        /*if (args.length < 2) {
            System.err.println("Usage: CommonFriends <inputFile>,<outputFile>,[neighborWindow]");
            return 1;
        }*/

        Path inputPath = new Path(args[0]);
        Path outputPath = new Path(args[1]);

        Configuration conf = getConf();
        Job job = Job.getInstance(conf, "FriendReCommendation");

        FileInputFormat.setInputPaths(job, inputPath);
        FileOutputFormat.setOutputPath(job, outputPath);

        // (key,value) generated by map()
         job.setMapOutputKeyClass(Text.class);
         job.setMapOutputValueClass(Text.class);

        // (key,value) generated by reduce()
        job.setOutputKeyClass(Text.class);
        job.setOutputValueClass(Text.class);

        job.setMapperClass(FriendRecommendationMapper.class);
        job.setReducerClass(FriendRecommendationReducer.class);
        // job.setCombinerClass(RelativeFrequencyCombiner.class);
        // job.setPartitionerClass(OrderInversionPartitioner.class);
        // job.setNumReduceTasks(3);

        long startTime = System.currentTimeMillis();
        job.waitForCompletion(true);
        THE_LOGGER.info("Job Finished in milliseconds: " + (System.currentTimeMillis() - startTime));
        return 0;
    }
}
